version: '3'

services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - AM_ENABLE_DIND=1
      - AM_FORCE_TEST_FAIL=$AM_FORCE_TEST_FAIL
      - AM_HOST_NAME=dev1
      - AM_HOST_OS_NAME=Linux
      - AM_HOST_USER_NAME=sonaalk
      - AM_HOST_VERSION=5.15.0-1072-aws
      - AM_REPO_CONFIG_CHECK=True
      # Use inferred path for `repo_config.py`.
      - AM_REPO_CONFIG_PATH=
      - CK_AWS_ACCESS_KEY_ID=$CK_AWS_ACCESS_KEY_ID
      - CK_AWS_DEFAULT_REGION=$CK_AWS_DEFAULT_REGION
      - CK_AWS_PROFILE=$CK_AWS_PROFILE
      - CK_AWS_S3_BUCKET=$CK_AWS_S3_BUCKET
      - CK_AWS_SECRET_ACCESS_KEY=$CK_AWS_SECRET_ACCESS_KEY
      - CK_ECR_BASE_PATH=$CK_ECR_BASE_PATH
      - CK_GIT_ROOT_PATH=/data/sonaalk/src/tutorials1
      - OPENAI_API_KEY=$OPENAI_API_KEY
      # - CK_ENABLE_DIND=
      # - CK_FORCE_TEST_FAIL=$CK_FORCE_TEST_FAIL
      # - CK_HOST_NAME=
      # - CK_HOST_OS_NAME=
      # - CK_PUBLISH_NOTEBOOK_LOCAL_PATH=$CK_PUBLISH_NOTEBOOK_LOCAL_PATH
      - CK_TELEGRAM_TOKEN=$CK_TELEGRAM_TOKEN
      # TODO(Vlad): consider removing, locally we use our personal tokens from files and
      # inside GitHub actions we use the `GH_TOKEN` environment variable.
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      # Inside GitHub Actions we use `GH_TOKEN` environment variable,
      # see https://cli.github.com/manual/gh_auth_login.
      - GH_TOKEN=$GH_ACTION_ACCESS_TOKEN
      # This env var is used by GH Action to signal that we are inside the CI.
      - CI=$CI
    image: ${IMAGE}
    # This is needed:
    # - for Docker-in-docker (dind)
    # - to mount fstabs
    privileged: true
    restart: "no"
    volumes:
      # TODO(gp): We should pass the value of $HOME from dev.Dockerfile to here.
      # E.g., we might define $HOME in the env file.
      - ~/.aws:/home/.aws
      - ~/.config/gspread_pandas/:/home/.config/gspread_pandas/
      - ~/.config/gh:/home/.config/gh
      # Shared data directories.
      - /data/shared:/shared_data
      - /data/shared2:/shared_data2
  # Mount `amp` when it is used as submodule. In this case we need to
  # mount the super project in the container (to make git work with the
  # supermodule) and then change dir to `amp`.
  app:
    extends:
      base_app
    volumes:
      # Move one dir up to include the entire git repo (see AmpTask1017).
      - /data/sonaalk/src/tutorials1:/app
      - /Users/saggese/src/git_gp1:/aux
    # Move one dir down to include the entire git repo (see AmpTask1017).
    working_dir: /app/tutorial_langchain
  linter:
    extends:
      base_app
    volumes:
      - /data/sonaalk/src/tutorials1/tutorial_langchain:/src
      - ../../:/app
    working_dir: /src
    environment:
      - MYPYPATH
  jupyter_server:
    command: devops/docker_run/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends:
      app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      # TODO(gp): Rename `AM_PORT`.
      - "${PORT}:${PORT}"

  # TODO(gp): For some reason the following doesn't work.
  #  jupyter_server_test:
  #    command: jupyter notebook -h 2>&1 >/dev/null
  #    extends:
  #      jupyter_server

  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends:
      app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - "${PORT}:${PORT}"