version: '3'
services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - CSFY_ENABLE_DIND=1
      - CSFY_FORCE_TEST_FAIL=$CSFY_FORCE_TEST_FAIL
      - CSFY_HOST_NAME=dev1
      - CSFY_HOST_OS_NAME=Linux
      - CSFY_HOST_USER_NAME=sonaalk
      - CSFY_HOST_VERSION=5.15.0-1075-aws
      - CSFY_REPO_CONFIG_CHECK=True
      - CSFY_REPO_CONFIG_PATH=
      - CSFY_AWS_ACCESS_KEY_ID=$CSFY_AWS_ACCESS_KEY_ID
      - CSFY_AWS_DEFAULT_REGION=$CSFY_AWS_DEFAULT_REGION
      - CSFY_AWS_PROFILE=$CSFY_AWS_PROFILE
      - CSFY_AWS_S3_BUCKET=$CSFY_AWS_S3_BUCKET
      - CSFY_AWS_SECRET_ACCESS_KEY=$CSFY_AWS_SECRET_ACCESS_KEY
      - CSFY_ECR_BASE_PATH=$CSFY_ECR_BASE_PATH
      - CSFY_GIT_ROOT_PATH=/app
      - CSFY_HELPERS_ROOT_PATH=/app/helpers_root
      - CSFY_IS_SUPER_REPO=1
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CSFY_TELEGRAM_TOKEN=$CSFY_TELEGRAM_TOKEN
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      - GH_TOKEN=$GH_ACTION_ACCESS_TOKEN
      - CSFY_CI=$CSFY_CI
    image: ${IMAGE}
    restart: 'no'
    volumes:
      - ~/.aws:/home/.aws
      - ~/.config/gspread_pandas/:/home/.config/gspread_pandas/
      - ~/.config/gh:/home/.config/gh
      - /data/shared:/shared_data
      - /data/shared2:/shared_data2
    privileged: true
  app:
    extends: base_app
    volumes:
      - /data/sonaalk/src/tutorials1:/app
    working_dir: /app/tutorial_prophet
  linter:
    extends: base_app
    volumes:
      - /data/sonaalk/src/tutorials1/tutorial_prophet:/src
      - ../../:/app
    working_dir: /src
    environment:
      - MYPYPATH
  jupyter_server:
    command: devops/docker_run/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
